function out = create_trapezoidal_gust(boundaries, angle_entry, angle_exit, amplitude, width)
    % CREATETRAPEZOIDALGUST Sets parameters fo a trapezoidal gust
    % Units
    % [boundaries.lat*] = rad
    % [boundaries.lon*] = rad
    % [boundaries.height*] = m
    % [angle_entry] = rad
    % [angle_exit] = rad
    % [amplitude] = m/s
    % [width] = m

    out = [boundaries.lat_start, ...
        boundaries.lat_end, ...
        boundaries.lon_start, ...
        boundaries.lon_end, ...
        boundaries.height_start, ...
        boundaries.height_end, ...
        angle_entry, ...
        angle_exit, ...
        amplitude, ...
        width];
end
