function out = create_trapezoidal_gust(lat_0, lon_0, height_0, width, gradient_north, gradient_south, gradient_east, gradient_west, amplitude)
    % CREATETRAPEZOIDALGUST Sets parameters fo a trapezoidal gust
    % Units
    % [lat_0] = rad
    % [lon_0] = rad
    % [height_0] = m
    % [width] = m
    % [gradient_north] = (m/s)/rad
    % [gradient_south] = (m/s)/rad
    % [gradient_east] = (m/s)/rad
    % [gradient_west] = (m/s)/rad
    % [amplitude] = m/s

    out = [lat_0, ...
        lon_0, ...
        height_0, ...
        width, ...
        gradient_north, ...
        gradient_south, ...
        gradient_east, ...
        gradient_west, ...
        amplitude];
end
